version: '3.8'
services:
  archives:
    build: .
    restart: on-failure
    environment:
      - BROADCASTIFY_USERNAME=XXXXX
      - BROADCASTIFY_PASSWORD=XXXXX
      - WEB_LOGIN_USERNAME=XXXXX            # This can be anything you want
      - WEB_LOGIN_PASSWORD=XXXXX            # This can be anything you want
      - FEED_ID=12345
      - REDIS_PASSWORD=passwordsuchstrong   # This can be anything you want
      - APP_SECRET_KEY=itsakadoozie         # This can be anything you want
    networks:
      - archive-net
    depends_on: 
      - redis
    ports:
      - 80:5000
  redis:
    image: bitnami/redis
    restart: on-failure
    networks:
      - archive-net
    environment:
      - REDIS_PASSWORD=passwordsuchstrong   # Must match redis password above

networks:
  archive-net: